version: 2.1
jobs:
  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t ahmad90/node-app:lts .
   
      - run:
          name: Push Docker image
          command: |
            docker login -u $username -p $password
            docker push ahmad90/node-app:lts

  add_tag:
    docker:
      - image: circleci/node:12.18
    steps:
      - checkout
      - run:
          name: Add build number as tag
          command: git tag $CIRCLE_BUILD_NUM
          
workflows:
  version: 2
  build_and_tag:
    jobs:
      - build
      - add_tag:
          requires:
            - build
          filters:
            branches:
              only: main
