version: 2.1
jobs:
  build:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t ahmad90/node-app:lts .
      - run:
          name: Run tests
          command: |
            docker run --rm ahmad90/node-app:lts npm test
  deploy:
    docker:
      - image: docker:stable-git
    steps:
      - run:
          name: Push Docker image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push ahmad90/node-app:lts
